version: '3.4'
name: backend

services:
  authentication:
    container_name: authentication
    image: ${DOCKER_REGISTRY-}authentication
    build:
      context: .
      dockerfile: Services/Authentication/Dockerfile
    #depends_on:
    #    - sqlstore
  coursemanagement:
    image: ${DOCKER_REGISTRY-}coursemanagement
    container_name: course_management
    build:
      context: .
      dockerfile: Services/CourseManagement/Dockerfile
    #depends_on:
    #    - sqlstore
networks:
  default:
   external:
    name: online_learning_platform
  
