services:
  authentication:
    environment: 
        ASPNETCORE_ENVIRONMENT: 'Development'
        ASPNETCORE_URLS: 'https://+:443;http://+:80'

        Database__ConnectionString: "server=sqlstore; port=3306; user=root; password=Password123!; database=authentication"
        
        Smtp__EmailAddress: 'karolis.zukaus@gmail.com'
        Smtp__EmailPassword: 'awtzbvzuypjgjlec'
        Smtp__TestEmail:  'karolis.zukaus@gmail.com'
        
        IP__Address: 'localhost'
        IP__Port: '44396'

        JwtSecret: 'Key+F0rTOk&n+Sig=1n6'

        EventBus__SubscriptionClientName: "CourseManagement"
        EventBus__HostName: "bunny"
        EventBus__Port: "5672"
        EventBus__UserName: "authentication"
        EventBus__Password: "Password123!"
        EventBus__RetryCount: "5"

    ports:
      - "44395:80"
      - "44396:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  coursemanagement:
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ASPNETCORE_URLS: 'https://+:443;http://+:80'
      
      Database__ConnectionString: "server=sqlstore; port=3306; user=root; password=Password123!; database=course_management"

      IP__Address: 'localhost'
      IP__Port: '44398'

      JwtSecret: 'Key+F0rTOk&n+Sig=1n6'

      EventBus__SubscriptionClientName: "Authentication"
      EventBus__HostName: "bunny"
      EventBus__Port: "5672"
      EventBus__UserName: "course_management"
      EventBus__Password: "Password123!"
      EventBus__RetryCount: "5"

    ports:
      - "44397:80"
      - "44398:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro