services:
  authentication:
    environment: 
        ASPNETCORE_ENVIRONMENT: 'Development'
        ASPNETCORE_URLS: 'https://+:443;http://+:80'

        Database__ConnectionString: "server=sqlstore; port=3306; user=root; password=Password123!; database=authentication"
        
        IP__Address: 'localhost'
        IP__Port: '44396'

        JwtSecret: 'oNVf9U3X+8vThOT9a7DRocqxtuFqpCrKg1e/2nvD3zqlb4tjsGuTh+mnspnVghmJ+3aoSQXPr3pcRqd3VZkz409QGoljHDffD2QcrmDFxn4A2yoX5ZWd4C5r98tnG4XB9pX+a+AiJJ8fj/cUS7DH42ZA1CNui18283rDihuGE1c='

        EventBus__SubscriptionClientName: "CourseManagement"
        EventBus__HostName: "bunny"
        EventBus__Port: "5672"
        EventBus__UserName: "authentication"
        EventBus__Password: "Password123!"
        EventBus__RetryCount: "5"

        ASPNETCORE_Kestrel__Certificates__Default__Path: "/certs/localhost.crt"
        ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/certs/localhost.key" 

    env_file:
      - auth_dev.env
    ports:
      - "44395:80"
      - "44396:443"
  coursemanagement:
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ASPNETCORE_URLS: 'https://+:443;http://+:80'
      
      Database__ConnectionString: "server=sqlstore; port=3306; user=root; password=Password123!; database=course_management"

      IP__Address: 'localhost'
      IP__Port: '44398'

      JwtSecret: 'oNVf9U3X+8vThOT9a7DRocqxtuFqpCrKg1e/2nvD3zqlb4tjsGuTh+mnspnVghmJ+3aoSQXPr3pcRqd3VZkz409QGoljHDffD2QcrmDFxn4A2yoX5ZWd4C5r98tnG4XB9pX+a+AiJJ8fj/cUS7DH42ZA1CNui18283rDihuGE1c='

      EventBus__SubscriptionClientName: "Authentication"
      EventBus__HostName: "bunny"
      EventBus__Port: "5672"
      EventBus__UserName: "course_management"
      EventBus__Password: "Password123!"
      EventBus__RetryCount: "5"

      ASPNETCORE_Kestrel__Certificates__Default__Path: "/certs/localhost.crt"
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/certs/localhost.key" 

    ports:
      - "44397:80"
      - "44398:443"
