FROM rabbitmq:3.12.0-management-alpine
ADD rabbitmq.config /etc/rabbitmq/
ADD rabbitmq_definitions.json /etc/rabbitmq/
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.config /etc/rabbitmq/rabbitmq_definitions.json
CMD ["rabbitmq-server"]
