version: '3.4'
name: backend

services:
  authentication:
    container_name: authentication
    image: ${DOCKER_REGISTRY-}authentication:dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/Authentication/Dockerfile
    depends_on:
       - mysql
       - rabbit
  coursemanagement:
    image: ${DOCKER_REGISTRY-}coursemanagement:dev
    container_name: course_management
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/CourseManagement/Dockerfile
    depends_on:
       - mysql
       - rabbit
  mysql:
    container_name: sqlstore
    image: ${DOCKER_REGISTRY-}mysql
    restart: unless-stopped
    ports:
     - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment: 
        MYSQL_ROOT_PASSWORD: 'Password123!'
        MYSQL_ROOT_HOST: '%'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'Password123!'
  rabbit:
    container_name: bunny
    hostname: bunny
    image: ${DOCKER_REGISTRY-}rabbit:dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
networks:
  default:
    name: online_learning_platform
    external: true 
volumes: 
  mysql_data:
  rabbitmq_data:
  
