version: '3.4'
name: olp_backend

services:
  proxy:
    container_name: proxy    
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - authentication
      - coursemanagement
      - coursecontentmanagement
  authentication:
    container_name: authentication
    restart: unless-stopped
    depends_on:
      - rabbit
    environment:
      JwtSecret: 'oNVf9U3X+8vThOT9a7DRocqxtuFqpCrKg1e/2nvD3zqlb4tjsGuTh+mnspnVghmJ+3aoSQXPr3pcRqd3VZkz409QGoljHDffD2QcrmDFxn4A2yoX5ZWd4C5r98tnG4XB9pX+a+AiJJ8fj/cUS7DH42ZA1CNui18283rDihuGE1c='
    env_file:
      - auth_dev.env
    working_dir: /src/Services/Authentication
  coursemanagement:
    container_name: course_management
    restart: unless-stopped
    depends_on:
      - rabbit
    working_dir: /src/Services/CourseManagement
  coursecontentmanagement:
    container_name: course_content_management
    restart: unless-stopped
    depends_on:
      - rabbit
    working_dir: /src/Services/CourseContentManagement
  rabbit:
    container_name: rabbit
    hostname: rabbit
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
networks:
  default:
    name: online_learning_platform