version: '3.4'
name: broker

services:
  rabbitmq:
    container_name: bunny
    image: rabbitmq:3.12.0-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
networks:
  default:
   external:
    name: online_learning_platform
  
